### ISSUE TITLE
Error to install the plugin 

### ISSUE THREAD

**Issue by drbelt27** [tritter/homebridge-brewer#7] opened 2022-01-04 18:27 UTC
![79BC3CCB-155E-4E91-948D-F11188FE8CA7](https://user-images.githubusercontent.com/64604481/148106232-38e56221-5f16-42e1-bfeb-4e3cff6a97fb.jpeg)

**Comment by tritter** [comment] 2022-01-04 18:52
@drbelt27 Thanks for trying my plugin. I also encountered this error in the new Bullseye release.
Could you try the following via ssh/terminal:
`sudo npm install -g @abandonware/noble`
`sudo -E -n npm install -g homebridge-brewer@latest --force`

**Comment by drbelt27** [comment] 2022-01-05 17:28
npm ERR! code 128npm ERR! An unknown git error occurrednpm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/abandonware/noble.gitnpm ERR! git@github.com: Permission denied (publickey).npm ERR! fatal: Could not read from remote repository.npm ERR! npm ERR! Please make sure you have the correct access rightsnpm ERR! and the repository exists.npm ERR! A complete log of this run can be found in:npm ERR!     /root/.npm/_logs/2022-01-05T17_27_14_903Z-debug.logroot@hom

**Comment by tritter** [comment] 2022-01-05 19:42
@drbelt27 ah looks like you don't have correct Github access. Please check the steps in this guide: https://docs.github.com/en/repositories/creating-and-managing-repositories/troubleshooting-cloning-errors

**Comment by drbelt27** [comment] 2022-01-06 15:51
I’m try but the procedure is complicated and the best is the installation directly with plugin manager of home bridge
I attend the new version of your plugin that solve this problem :)

**Comment by borisogdoris** [comment] 2022-01-08 10:28
I have the same issue.

**Comment by tritter** [comment] 2022-01-10 06:11
@drbelt27 @borisogdoris I'm sorry to hear I also expected issues last time I installed a fresh Pi. So I think it might related to the new linux release. Could you both post your systems? (OS, is also displayed on the homebridge page)

**Comment by borisogdoris** [comment] 2022-01-10 06:49
Raspbian GNU/Linux Buster (10)
Node.js Version | v16.13.1
Npm Version | v8.1.

**Comment by drbelt27** [comment] 2022-01-10 16:05
Raspbian GNU/Linux Bullseye (11) 
Version Node.js  v16.13.1
Npm v8.3.0

**Comment by tritter** [comment] 2022-01-14 08:03
@borisogdoris @drbelt27 Thanks a lot, sorry for my delay. I will have new Sd-Cards next week to test some fresh pis 🍰  Until then I think the problem is fixed by 2.0.6, could you both test?

You both also added the bluetooth library required for bluetooth before the plugin (see README)? 
```sudo apt-get install bluetooth bluez libbluetooth-dev libudev-dev```

Thanks a lot, sorry for the delay! Still hope you can enjoy coffee ☕️

**Comment by borisogdoris** [comment] 2022-01-14 09:54
Now it works! Thank you! :)

**Closed as completed** 2022-01-21 06:43 UTC
Labels: bug
